services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
